### ISSUE TITLE
Mark twingle contributions / recurring contributions

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.twingle#11]
Currently there is no reliable way to know whether an existing contribution or recurring contribution has been created by twingle.

**Comment by jensschuppe** [comment]
@bjendres Since there's the `source` field which is configurable per Twingle profile and the transaction ID prefix, is there still a need for some extra sort of marker/tag for contributions created by the Twingle API?

**Comment by jensschuppe** [comment]
@bjendres Is this still relevant since #9 has been rejected in favor of #20?

I'm moving it to the 1.3 milestone, anyway.
