### ISSUE TITLE
Correctly differentiate initial recurring and subsequent contributions and link them

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.twingle#23]
Currently, all subsequent contributions belonging to a recurring contribution will be created as a recurring contribution themselves and not have any link to the initial recurring contribution.

Twingle are now sending a parameter `parent_trx_id` which can be used to identify the initial recurring contribution and link subsequent single contributions to it.

**Comment by bjendres** [comment]
Will be released with ``1.2``
