### ISSUE TITLE
Custom fields mapping not working - unnecessary json_decode()

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.twingle#25]
Since Twingle submits all parameters within the `json`parameter, there is no need to `json_decode()` the `custom_fields` parameter again, as this causes the custom field mapping to not work at all.

**Comment by jensschuppe** [comment]
This has positive test feedback by @MarcMichalsky - therefore closing.

**Comment by bjendres** [comment]
Will be released with ``1.2``
