### ISSUE TITLE
More campaign options

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.twingle#27]
If there is a campaign (either passed by Twingle or defined in the profile) there is multiple ways where it could be set:

- contribution
- recurring contribution
- SEPA mandate
- membership

Since the required behaviour might vary greatly between organisations, we would like to make this configurable.

This replaces/extends #26

**Comment by jensschuppe** [comment]
This should then be a checkboxes field with the above-mentioned options, I guess.

**Comment by bjendres** [comment]
> This should then be a checkboxes field with the above-mentioned options, I guess.

It's a multi-select field

**Comment by bjendres** [comment]
Will be released with ``1.2``
