### ISSUE TITLE
Twingle recurring installments also trigger membership creation

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.twingle#31]
Twingle installments will be posted to the same profile as the original one (see #23). That, however, means, that it would also generate a new membership each time (see #5), if that was configured for the profile.

**Comment by jensschuppe** [comment]
There are the two following settings for selecting whether to create memberships:
- Create membership of type
- Create membership of type (recurring)

Can you confirm that only the latter is being set to create memberships of a type and subsequent installments of an initial recurring donation are triggering the creation of a new membership of that type?

**Comment by bjendres** [comment]
While reading through the code, it looks like this only in the latter case. I don't have confirmation, because in our scenario both were active.

**Comment by bjendres** [comment]
But that's the point, even if it's an installment (rather than the first contribution) it will create another membership (recurring), because ``donation_rhythm`` is _not_ ``one_time``.

**Comment by bjendres** [comment]
I'm already looking into fixing this, though.

**Comment by bjendres** [comment]
@jensschuppe do you think this would work: https://github.com/systopia/de.systopia.twingle/commit/4ec0fef825516738d22c65207a417525b0cf2345

Or is the ``parent_trx_id`` also set in the initial submission?

**Comment by jensschuppe** [comment]
The initial submission has this for `parent_trx_id`:

```json
"parent_trx_id": null
```

So, this should work with an `empty()` check.

Care to put the condition into an `elseif` to avoid one more nesting level?

**Comment by bjendres** [comment]
@jensschuppe this way? https://github.com/systopia/de.systopia.twingle/commit/da790863b574ec346839e95af1df7b1d5541145c

**Comment by jensschuppe** [comment]
@bjendres Exactly, thanks!

**Comment by bjendres** [comment]
Will be released with ``1.2``

**Comment by bjendres** [comment]
There was still a bug in the workflow, this should be fixed with ``1.2-beta3``

**Comment by jensschuppe** [comment]
Will be released with `1.2`
