### ISSUE TITLE
Twingle's double-opt-In for e-mail is not getting mapped

### ISSUE THREAD

**Issue by MarcMichalsky** [systopia/de.systopia.twingle#34]
Hello community,

The Twingle API call does contain a value for subscribing to the newsletter regardless of whether the Double-Opt-In was confirmed by the contact or not.

This leads to the situation that someone will receive the newsletter regardless of his confirmation of the Double-Opt-In.

Of course an organization could deactivate the Double-Opt-In on the Twingle side and realize it by it self with CiviCRM but I would like to suggest to implement a new entity to transmit the user confirmation between Twingle and the Extension.

**Comment by jensschuppe** [comment]
Is Twingle sending their own double opt-in messages for newsletter subscriptions?

If not, this will involve replacing the call to `GroupContact.create` with a call to `MailingEventSubscribe.create` for using CiviCRM's double opt-in feature here: https://github.com/systopia/de.systopia.twingle/blob/675b682e0ea4267f498d81b48ce16f2c6e5fcf6f/api/v3/TwingleDonation/Submit.php#L487-L497

If Twingle _is_ sending their own double opt-in messages, CiviCRM will have to create `GroupContact` entries with a "Pending" status and Twingle will need to issue another API call to the Twingle API for updating the status.

@MarcMichalsky Feel free to create a PR if you like, for whatever scenario is true.

**Comment by webworka** [comment]
> Is Twingle sending their own double opt-in messages for newsletter subscriptions?

Depends on the customer settings. Twingle *can* send a DOI message but must not. It's also possible that customers configured newsletter provider to send the DOI main. In this case twingle will not send the DOI message and will also know nothing about the DOI.

Nevertheless: I'ts an interesting idea to use (optional?) the CiviCRM DOI feature. In this case customers should disable the DOI on twingle and enable it in the CiviCRM.

**Comment by jensschuppe** [comment]
@webworka Implementing CiviCRM's DOI feature (`MailingEventSubscribe`) would be another task. I changed the issue title to reflect we're targeting Twingle's own DOI thing here. I'm not sure what else would be necessary for syncing DOI status in CiviCRM when using external mailing providers. Let's keep that in the backlog for now. Thanks for the heads-up though!

**Comment by jensschuppe** [comment]
See https://github.com/systopia/de.systopia.twingle/issues/36#issuecomment-1102760849.

**Comment by MarcMichalsky** [comment]
I don't think we need this feature anymore. It is likely that there are organizations that would prefer to use Twingle's DOI without CiviCRM.

For those who want to use CiviCRM to send the DOIs, you can disable the DOI in TwingleMANAGER and check the I checkbox in the Twingle API profile (the feature will be released in [1.3](https://github.com/systopia/de.systopia.twingle/milestone/3)).
