### ISSUE TITLE
Use CiviCRM's double opt-in feature for newsletter subscription

### ISSUE THREAD

**Issue by MarcMichalsky** [systopia/de.systopia.twingle#36]
As already mentioned in #34, the Twingle double opt-in setting is not getting mapped into CiviCRM.

In order to meet the requirements of the GDPR, it is necessary to receive a double opt-in confirmation before contacts are added to a newsletter group.

A solution would be the usage of CiviCRM's own double opt-in feature.

**Comment by bjendres** [comment]
Thanks @MarcMichalsky. @jensschuppe will have a look at this when he's back from his vacation (August 11th).

**Comment by jensschuppe** [comment]
Will be released with 1.3. Thanks @MarcMichalsky!

**Comment by mariav0** [comment]
Hi there,
I am still having the same issue.
If I select "double opt-in" in twingle, I am getting an email from twingle but it does not matter if I confirm or not. 
So I disable "double-opt-in" but then I have to use 2 groups - one group which is mapped in the twingle profile and another one for the Pending Subscription which I trigger via CiviRule. Is there any other solution?

**Comment by jensschuppe** [comment]
> If I select "double opt-in" in twingle, I am getting an email from twingle but it does not matter if I confirm or not.

That's because Twingle's DOI is not yet implemented (#34 still being open).

If I got #38 right, there's no need for a second group. The API will just decide whether or not to use DOI depending on the parameter `newsletter_double_opt_in` being set or not in the profile. This works with the same group. With DOI, contacts are added with the status "Pending"; without, they're added with the status "Added". @MarcMichalsky might help you better understand the workflow.

I'm not sure how CiviRules is supposed to interfere in your setup, but Twingle API's workflow seems quite well-defined to me in terms of CiviCRM DOI.

**Comment by MarcMichalsky** [comment]
Hi Maria,

I don't understand for what purpose you are using CiviRules and the two groups.

In commit [72a3515](https://github.com/systopia/de.systopia.twingle/commit/72a3515e8ae4ba670a8e79edcc44e23278be3c1b) we added a field "Use Double-Opt-In for newsletter" to the Twingle API profiles. If you check this box, CiviCRM will take care of double opt-in emails and group memberships. When someone signs up for the newsletter, it adds the contact with a pending status to the newsletter group configured in the profile and sends a confirmation link. When the person clicks the link, the group membership status changes to active.

**Comment by mariav0** [comment]
Thanks for your quick response, @jensschuppe 

How can the API decide what to use? If I select DOI in Twingle it does not work - as you said. And if I don't, it just does not send the email from twingle but still adds the contact directly to the group. There is no "Pending". At least it did not work in my tests.

The CiviRule triggers when adding a contact to a group and then I choose the action "Create Pending Subscription" for my second DOI group.

**Comment by mariav0** [comment]
Ahh I think I know why now. I didn't pull that commit since it was never released, right?

**Comment by MarcMichalsky** [comment]
It should be included in [1.2.2](https://github.com/systopia/de.systopia.twingle/releases/tag/1.2.2). The commit 72a3515e8ae4ba670a8e79edcc44e23278be3c1b is listed there: https://github.com/systopia/de.systopia.twingle/compare/1.2.2...master

**Comment by mariav0** [comment]
I see, I did not notice there was a new release after 1.2.1. CiviCRM does not show that there is a new version.

**Comment by MarcMichalsky** [comment]
Ah, sorry, my mistake. I thought it was already included in `1.2.2`. Actually I use the git repository on `1.3-alpha1` instead of the release package.

**Comment by mariav0** [comment]
Sorry, I have overlooked your comment about the release 1.3.
DOI is working now. Thank you both!

**Comment by jensschuppe** [comment]
Released with `1.3-beta1`.
