### ISSUE TITLE
Settings for newsletter groups: show only newsletter groups

### ISSUE THREAD

**Issue by MarcMichalsky** [systopia/de.systopia.twingle#37]
The settings field for newsletter groups shows all kinds of groups.
Wouldn't it be better to show only newsletter groups?

**Comment by bjendres** [comment]
Thanks @MarcMichalsky. @jensschuppe will have a look at this when he's back from his vacation (August 11th).

**Comment by MarcMichalsky** [comment]
Sorry, I was wrong.
The settings field for newsletter groups shows only newsletter groups, like it should.
Unfortunately the usage of MailingEventSubscribe.create only allows to add contacts to newsletter groups which are also public.

**Comment by bjendres** [comment]
Thanks anyway :)
