### ISSUE TITLE
"Data too long" when saving many profiles

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.twingle#42]
Since profiles are being stored as a single CiviCRM setting, which have a column length of 64k (MySQL data type `TEXT`), storing many™ profiles my exceed this limit.

Problem 1 is that the number of profiles is limited due to that column length.

Problem 2 is even worse, because CiviCRM did not throw `Data too long` errors until a recent version and cut the serialized value, which would cause corrupted data (i.e. profile data not be loaded anymore)

We should consider storing profiles as separate setting entries or somewhere else. The CiviCRM settings system does not seem scalable easily.

**Comment by jensschuppe** [comment]
This got merged for `1.4?? already.

**Comment by bjendres** [comment]
> This got merged for 1.4 already.

But it's not released yet. Regardless, the #70 bug is observed on with on 1.4-alpha1.

**Comment by bjendres** [comment]
> This could eventually be migrated to use [systopia/config-profiles](https://github.com/systopia/config-profiles).

Yes, but that would have to extended to include the ``access_counter``.
