### ISSUE TITLE
Change campaign_id data type to string for compatibility with de.forumzfd.twinglecampaign extension

### ISSUE THREAD

**Issue by MarcMichalsky** [systopia/de.systopia.twingle#44]
The [de.forumzfd.twinglecampaign](https://lab.civicrm.org/Marc_Michalsky/de-forumzfd-twinglecampaign) extension uses UIDs to match incoming donations with its campaigns.

Changing the data type for `campaign_id` to a string allows the de.forumzfd.twinglecampaign extension to:
1. match the right campaign
2. write the id of the identified campaign into the `campaign_id` parameter
3. let the de.systopia.twingle extension do the rest of the work

**Comment by jensschuppe** [comment]
Released with `1.3-beta1`.
