### ISSUE TITLE
Deprecated: Array and string offset access syntax with curly braces is deprecated in twingle.civix.php on line 246

### ISSUE THREAD

**Issue by MarcMichalsky** [systopia/de.systopia.twingle#51]
![Screenshot 2021-08-31 at 10-59-15 CiviCRM Home CiviCRM Sandbox on Drupal](https://user-images.githubusercontent.com/24728186/131475776-6372e4af-53f5-4a89-9d6d-5cc05416292f.png)

This error occurs in the [civicrm-buildkit-docker](https://github.com/michaelmcandrew/civicrm-buildkit-docker) (PHP 7.4.22).

**Comment by MarcMichalsky** [comment]
Looks like this is a problem in the code that was automatically generated by civix. I got the same issue in my extension. 😅

**Comment by bjendres** [comment]
Yes, exactly, we just have to run ``civix`` again with the current version to regenerate the files.

**Comment by MarcMichalsky** [comment]
> Yes, exactly, we just have to run `civix` again with the current version to regenerate the files.
If this is is the preferred way to fix this issue, I will close my PR #52.

**Comment by jensschuppe** [comment]
cadf895def3b04b5e0cdd5f475cd268da02f49a3 regenerates the `twingle.civix.php` file with latest Civix. @MarcMichalsky Could you run a short test to see if that solves the issue and does not impose other problems (which it really shouldn't)? This will then replace your PR #52.

**Comment by MarcMichalsky** [comment]
> [cadf895](https://github.com/systopia/de.systopia.twingle/commit/cadf895def3b04b5e0cdd5f475cd268da02f49a3) regenerates the `twingle.civix.php` file with latest Civix. @MarcMichalsky Could you run a short test to see if that solves the issue and does not impose other problems (which it really shouldn't)? This will then replace your PR #52.

With commit [cadf895](https://github.com/systopia/de.systopia.twingle/commit/cadf895def3b04b5e0cdd5f475cd268da02f49a3) there are no more errors occurring in my buildkit environment. I was also able to do a successfully `TwingleDonation.submit` call.

Looks fine to me. Thanks!

**Comment by jensschuppe** [comment]
@MarcMichalsky Thanks, I'll close this, since the commit is on `master` already.

**Comment by jensschuppe** [comment]
Will be released with `1.3` and `1.2.2`.
