### ISSUE TITLE
NL double opt-in: Check if there is an existing subscription already

### ISSUE THREAD

**Issue by mariav0** [systopia/de.systopia.twingle#54]
This issue is related to the following solved issue: 
https://github.com/systopia/de.systopia.twingle/issues/36

I have noticed that I get a group subscription mail when I am already in this group. This creates a new pending group subscription which could be in worst case not accepted. 
I think it could be good to check before if there is a subscription for this specific group already.
What do you think, @MarcMichalsky @jensschuppe ?

**Comment by MarcMichalsky** [comment]
Hi @mariav0,
I tested it and I can't reproduce this behavior.

> I think it could be good to check before if there is a subscription for this specific group already.

This is exactly what happens [here](https://github.com/systopia/de.systopia.twingle/blob/29e0b50cd15ed014a6ccb2310ee2f28acd36269f/api/v3/TwingleDonation/Submit.php#L512-L540).

Is the selected group a public newsletter group?

**Comment by MarcMichalsky** [comment]
No problem. Thanks for the extensive testing and reporting!
