### ISSUE TITLE
Can't enter "Configure extension settings"

### ISSUE THREAD

**Issue by ma8bi4ne** [systopia/de.systopia.twingle#56]
When clicking the button "Configure extension settings" I am presented with a white blank page with the following text:

`The website encountered an unexpected error. Please try again later.`

Rather unspecific error, so where can one start looking for the origin of the problem? Does anybody know this behaviour?

**Comment by jensschuppe** [comment]
There should be a specific error logged in the CiviCRM logs (`ConfigAndLog` directory, e.g. when in Drupal at `sites/default/files/civicrm/ConfigAndLog`, look for the file with the latest modified date). Please provide steps to reproduce (with installed extension and CiviCRM core version) and the error message, if any.

**Comment by ma8bi4ne** [comment]
Unfortunately the logfile is empty in the path you specified.
CiviCRM-Version is 5.51.1
PHP is 8.0.20

**Comment by jensschuppe** [comment]
There might be an incompatibility of the extension (wich you did not tell us the installed version of) with PHP 8.0 - I won't have the time to check that anytime soon, pinging @MarcMichalsky as he knows the extension quite well.

**Comment by ma8bi4ne** [comment]
Sorry, forgot about that - that is Twingle API 1.3

**Comment by jensschuppe** [comment]
@ma8bi4ne Could you verify whether the fix @MarcMichalsky provided in #61 fixes the problem you described?

**Comment by jensschuppe** [comment]
Setting to fixed via #61.
