### ISSUE TITLE
SepaMandate is created without setting campaign_id

### ISSUE THREAD

**Issue by RoWo-DS** [systopia/de.systopia.twingle#60]
We use [de.systopia.twingle](https://github.com/systopia/de.systopia.twingle) and [de.forumzfd.twinglecampaign](https://de.forumzfd.twinglecampaign) with [org.project60.sepa](https://github.com/Project60/org.project60.sepa). We observe that donations made as bank transfer are assigned correctly to a corresponding CiviCRM-Campaign, using the url-paramter `tw_cid`. But with the same test use case, only differing by replacing bank transfer with SEPA DD One-off Transaction, the donation is not assigned to any CiviCRM-Campaign.

I am quite new to CiviCRM and dont have experience with PHP, so please excuse if I am wrong with the following hypothesis.

Just before [SepaMandate is created](https://github.com/systopia/de.systopia.twingle/blob/master/api/v3/TwingleDonation/Submit.php#L693), the [campaign_id is set](https://github.com/systopia/de.systopia.twingle/blob/master/api/v3/TwingleDonation/Submit.php#L690). However, as [the campaign_id is set with context 'mandate' and a context not being an array](https://github.com/systopia/de.systopia.twingle/blob/master/api/v3/TwingleDonation/Submit.php#L690), a [backward compatibility](https://github.com/systopia/de.systopia.twingle/blob/master/CRM/Twingle/Submission.php#L411) is preventing the campaign_id to be set, while [campaign_id is removed through the call of setCampaign](https://github.com/systopia/de.systopia.twingle/blob/master/CRM/Twingle/Submission.php#L405). That is resulting in the loss of the campaign_id, even when [it was set before](https://github.com/systopia/de.systopia.twingle/blob/master/api/v3/TwingleDonation/Submit.php#L618).

I guess that a solution would be to add 'mandate' to the [enabled_contexts](https://github.com/systopia/de.systopia.twingle/blob/master/CRM/Twingle/Submission.php#L411) array.

**Comment by bjendres** [comment]
>  a solution would be to add 'mandate' to the [enabled_contexts](https://github.com/systopia/de.systopia.twingle/blob/master/CRM/Twingle/Submission.php#L411) array.

I'm not sure I can follow you. Adding the campaign to the mandate should already be possible by adding the "Sepa Mandate" option to the "Set Campaign for" setting in the Twingle profile. 

Or am I missing something here? What do you mean by "as [the campaign_id is set with context 'mandate' and a context not being an array](https://github.com/systopia/de.systopia.twingle/blob/master/api/v3/TwingleDonation/Submit.php#L690)"

**Comment by RoWo-DS** [comment]
Thanks Björn for the fast answer!

Now I understand the "Set Campaign for" option and with your hint it works as expected.

I thought it will also work if only `Zuwendung` ("`contribution`"?) is selected, but with `SEPA Mandate` selected in addition it works:
![grafik](https://user-images.githubusercontent.com/107472325/215767434-98d31ba8-4325-45a9-a1a8-5a6b8bc40972.png)

Thanks again!

**Comment by bjendres** [comment]
> I thought it will also work if only `Zuwendung` ("`contribution`"?) is selected, but with `SEPA Mandate` selected in addition it works

Yes, I believe the "contribution" ("Zuwendung") option refers to a simple contribution record, not one connected to CiviSEPA.
