### ISSUE TITLE
Error on settings page - broken API parameter structure for activity assignee EntityRef field

### ISSUE THREAD

**Issue by MarcMichalsky** [systopia/de.systopia.twingle#61]
This issue may be related to #56.

When opening the _Twingle API - Generic Settings_ page, an error message is displayed:

![Screenshot 2023-02-14 at 09-28-15 Twingle API Settings CiviCRM forumZFD](https://user-images.githubusercontent.com/24728186/219043979-81de6fb3-c4a9-44a7-9172-7323f61868e5.png)

`contact_type` is an array, but only strings are allowed in `$attributes`.

![Bildschirmfoto vom 2023-02-14 09-07-02](https://user-images.githubusercontent.com/24728186/218694856-4afb9db4-aa21-4545-87c9-7cefea27f696.png)

The problem is the `twingle_protect_recurring_activity_assignee` selection field, which seems to pass an invalid array structure to `$this->addEntityRef()`.

https://github.com/systopia/de.systopia.twingle/blob/1b684624016a72f251f6b621b94799f759b2485e/CRM/Twingle/Form/Settings.php#L92-L99

According to the [documentation](https://docs.civicrm.org/dev/en/latest/framework/quickform/entityref/#php-from-a-buildform-function), the array passed to `$this->addEntityRef()` must be structured as follows:

```php
// Use the 'option_value' entity for most "option" lists, e.g. event types, activity types, gender, individual_prefix, custom field options, etc.
$this->addEntityRef('field_5', ts('Activity Type'), [
  'entity' => 'option_value',
  'api' => [
    'params' => ['option_group_id' => 'activity_type'],
  ],
  'select' => ['minimumInputLength' => 0],
]);
```

If the array is structured correctly, the problem is solved:

![Bildschirmfoto vom 2023-02-14 10-31-46](https://user-images.githubusercontent.com/24728186/218697076-4bf5b0eb-0097-4071-8487-f0b43e3a978a.png)

**Comment by jensschuppe** [comment]
Thanks @MarcMichalsky!
