### ISSUE TITLE
XCM setting causes empty entries

### ISSUE THREAD

**Issue by mariav0** [systopia/de.systopia.twingle#64]
**Current Settings**

XCM:
Fill (Address) -> if contact has no address with same type

![image](https://user-images.githubusercontent.com/70949178/225021709-67af9f1d-d9d6-450b-acbd-0666aa14c884.png)

Twingle:
![image](https://user-images.githubusercontent.com/70949178/225021897-09e7f9d1-866f-488a-949b-8e70873c7e0d.png)

**Current behavior**
Creates an empty entry 

**Expected behavior**
Creates no entry when no information (or only country) is filled

**Workaround**
Fill (Address) -> never

![image](https://user-images.githubusercontent.com/70949178/225038078-ef7cac85-c555-48cd-bae4-28b58f326a64.png)

Unfortunately this workaround is not applicable on any instances.

CiviCRM 5.58.1
Twingle 1.3
XCM 1.9-alpha6

There has been a similar issue of this topic already: https://github.com/systopia/de.systopia.twingle/issues/47

**Comment by jensschuppe** [comment]
Hi @mariav0! This is most likely due to the older version of XCM. There has been systopia/de.systopia.xcm#94. You should try the latest stable version of XCM, which is `1.9`. Let us know if that fixes the issue!

**Comment by mariav0** [comment]
Hi @jensschuppe, 
Thanks for your quick response. As mentioned I have XCM 1.9-alpha6 installed. So I guess it's a different issue?

**Comment by mariav0** [comment]
Oh yes, of course, my bad. I don't know where my head was at when I was responding. It's working with the update, thanks @jensschuppe :)
