### ISSUE TITLE
generic payment method not mapped yet

### ISSUE THREAD

**Issue by mariav0** [systopia/de.systopia.twingle#67]
When using generic payment method (in german "generisches Zahlungsverfahren") an error occurs:

 "Payment method could not be matched to existing payment instrument."

I am not a developer. So I am not sure if it would be enough to add some lines here: https://github.com/systopia/de.systopia.twingle/blob/master/CRM/Twingle/Profile.php

```
  public static function paymentInstruments() {
    return [
      'pi_generic' => E::ts('Generic Payment Method'),
    ];
  }

  public static function createDefaultProfile($name = 'default') {
    return new CRM_Twingle_Profile($name, [
     'pi_generic'  => NULL,
      ],
    ]
  }
```
Is there anything else needed?
@MarcMichalsky: Would you have time to have a look on this issue with me?

**Comment by MarcMichalsky** [comment]
Right now I don't know what exactly the generic payment method means. I do see that it can be activated by Twingle support, but I have no idea what it actually is. And it was never mentioned to me by Twingle either.

Assuming that the generic payments end up at Twingle and later on your bank account in some way, we would need to add the `generic` payment method in some places in the code, to create a setting to map them in CiviCRM (to define payment instrument and status).

First we need to find out if it is always called `generic` in the transfer (like `paypal` or `sofortueberweisung`).

Do you use CiviProxy? If so, could you search the logs and tell me what exactly was transferred by Twingle?
Alternatively, could you download your transactions as CSV in TwingleMANAGER and tell me what is written in the `payment_method` field?

**Comment by mariav0** [comment]
Hi @MarcMichalsky,

First of all, thanks for your quick response. 
I do not use CiviProxy but I have downloaded the CSV and the entry in the `payment_method` field is `generic`.

**Comment by MarcMichalsky** [comment]
Then we would just have to add `generic`, as was done here 6132e7ad8023603843f0d0619e6eb50ea7a26a85, 945992d8beb919d8c1eb7f2efa435ed2ddf9d235.

**Comment by MarcMichalsky** [comment]
If you create a PR, I will be happy to test it in my test environment.

**Comment by jensschuppe** [comment]
I'd like to have some clarification on what the *generic payment method* actually is. *Twingle* have not documented or mentioned that payment instrument. Maybe @webworka could shed some light?

**Comment by webworka** [comment]
@jensschuppe Sure, no problem. As @mariav0 mentioned above:

> The generic payment method is more a relic, which was used for a while for crowdfunding. But rather experimental and not for productive use.

That's basically it. We used this in the past for two or three customers that want to collect userdata for crowdfunding campaigns and do the payment later on. Customers can set theire own icon and name for this "payment" method. In most cases this was used for banktransfer or standing orders.
At the moment there is only one customer that uses it for standing orders. That is the only useful case I can think of at the moment. So mapping this to banktransfer as payment method will be correct in 99% of the cases.
