### ISSUE TITLE
Saving a profile under the name of another profile causes it to be overwritten

### ISSUE THREAD

**Issue by MarcMichalsky** [systopia/de.systopia.twingle#70]
If you change the name of a profile to that of another, already existing profile, this other profile is overwritten instead of the current profile. 

This is probably due to the fact that the storage of the profiles in a database table was implemented later on.

At least at this place the database ID should be used instead of the profile name:
https://github.com/systopia/de.systopia.twingle/blob/518f8809c7d8167c350b0ba3afd7f59da540661a/CRM/Twingle/Form/Profile.php#L142-L146

I would be happy to fix this, as this bug indirectly affects the implementation of the Twingle Shop #69.

**Comment by bjendres** [comment]
> I would be happy to fix this, as this bug indirectly affects the implementation of the Twingle Shop https://github.com/systopia/de.systopia.twingle/pull/69.

You'd be very welcome to do so! Just make sure you catch all the cases :)

But even if you change the primary identifier to the ID, we should still make sure profiles cannot have the same name - but that might already be the case anyway...

**Comment by MarcMichalsky** [comment]
Well, there is already a [mechanism](https://github.com/systopia/de.systopia.twingle/blob/518f8809c7d8167c350b0ba3afd7f59da540661a/sql/civicrm_twingle_profile.sql#L14) to avoid duplicate names.

But you are right, I will include some additional validation for that – and also for the `project_ids` which should not be defined in more than one profile.

**Comment by bjendres** [comment]
> I will include some additional validation for that

great.

Just to be sure: you are aware of #42, right?

**Comment by MarcMichalsky** [comment]
Solved in d9e51c67f6f50aa8a3825bb9496e4e4fd04ee70c
