### ISSUE TITLE
Fix issues introduced in 8bcdff4

### ISSUE THREAD

**Issue by MarcMichalsky** [systopia/de.systopia.twingle#86]
In commit 8bcdff4, some of the logic for testing whether or not  `$profile->getAttribute()` returns a configuration value was changed to use `isset()` or `is_string()` instead of `!empty()`.  

The problem is that `$profile->getAttribute()` looks for the attribute name in it's `$data` property, which also contains the attribute names for config values that are not set (the value is then an empty string).

I suggest changeing `$profile->getAttribute()` as follows:
```php
public function getAttribute($attribute_name, $default = NULL) {
    return $this->data[$attribute_name] ?? $default;
}
```

```php
public function getAttribute($attribute_name, $default = NULL) {
    return !empty($this->data[$attribute_name]) ? $this->data[$attribute_name] : $default;
}
```

Or should we just revert commit 8bcdff4 instead?

**Comment by jensschuppe** [comment]
Hm, seems my assumptions weren't correct everywhere. The point of those changes was to replace the use of `empty()`, so introducing `empty()` again does not seem right. We don't want to use `empty()` in general, as it's too broad of a comparison and does not take types into account.

Could you list the insufficient comparisons you noticed in 8bcdff4a855f621fec11ba255112c1d4ff57046e? I'll have a look at them again …
