### ISSUE TITLE
a lot of warnings "Permission 'access Twingle API' should be declared with 'label' and 'description' keys."

### ISSUE THREAD

**Issue by umeyermartin** [systopia/de.systopia.twingle#97]
![ksnip_20240804-172033](https://github.com/user-attachments/assets/137b4ad0-63a8-47d3-a0a1-14bd8b4e7a4d)
![ksnip_20240804-172100](https://github.com/user-attachments/assets/e1731b65-6845-4516-b1ee-96b2eb124fcc)

Looks like that core functionality should be streamlined and extension developers are forced to adjust theit coding

**Comment by bjendres** [comment]
This was fixed with 75d9516da0926662b37333ed7809a9039967285c, and is part of the extension since version ``1.4-beta1``. 

@umeyermartin Could you confirm that?
